import React from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle } from 'lucide-react';
import apiClient from '../api/client';

export const ServiceBreaks: React.FC = () => {
  const { data, isLoading } = useQuery({ queryKey: ['serviceBreakDue'], queryFn: async () => (await apiClient.get('/api/service-breaks/due')).data });
  const { data: active } = useQuery({ queryKey: ['serviceBreakActive'], queryFn: async () => (await apiClient.get('/api/service-breaks/active')).data });
  const queryClient = useQueryClient();
  const startMutation = useMutation({ mutationFn: (row: any) => apiClient.post(`/api/service-breaks/appointment/${row.id}/start`, { employeeId: row.employee.id, breakStartDate: new Date().toISOString().slice(0, 10), breakEndDate: new Date(Date.now() + 10 * 86_400_000).toISOString().slice(0, 10), reason: 'Mandatory service break' }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['serviceBreakDue'] }) });
  const completeMutation = useMutation({ mutationFn: (id: string) => apiClient.patch(`/api/service-breaks/${id}/complete`), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['serviceBreakDue'] }); queryClient.invalidateQueries({ queryKey: ['serviceBreakActive'] }); } });
  const rows = data || [];
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}><div className="card" style={{ padding: 0 }}>
    <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--border-color)', display: 'flex', gap: 10, alignItems: 'center' }}><AlertTriangle color="var(--color-warning)" /><div><h3 style={{ margin: 0 }}>Service Break Due List</h3><p style={{ margin: '4px 0 0', fontSize: 13, color: 'var(--text-secondary)' }}>Appointments requiring a mandatory service-break action in the next 30 days.</p></div></div>
    <div className="table-container" style={{ border: 'none' }}>{isLoading ? <p style={{ padding: 24 }}>Loading…</p> : <table className="data-table"><thead><tr><th>Employee</th><th>Department</th><th>Appointment</th><th>Break Due</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td><strong>{row.employee?.name}</strong><br /><small>{row.employee?.code}</small></td><td>{row.department?.name}</td><td>{row.orderNumber}</td><td>{row.breakDueDate ? new Date(row.breakDueDate).toLocaleDateString() : '—'}</td><td><span className="badge badge-warning">{row.employee?.status}</span></td><td><button className="btn btn-primary" disabled={startMutation.isPending} onClick={() => startMutation.mutate(row)}>Start break</button></td></tr>)}{rows.length === 0 && <tr><td colSpan={6} style={{ padding: 24, textAlign: 'center' }}>No service breaks due.</td></tr>}</tbody></table>}</div>
  </div><div className="card" style={{ padding: 0 }}><div style={{ padding: '16px 24px', borderBottom: '1px solid var(--border-color)' }}><h3 style={{ margin: 0 }}>Active Service Breaks</h3></div><div className="table-container" style={{ border: 'none' }}><table className="data-table"><thead><tr><th>Employee</th><th>Start</th><th>End</th><th>Action</th></tr></thead><tbody>{(active || []).map((row: any) => <tr key={row.id}><td>{row.employee?.name} ({row.employee?.code})</td><td>{new Date(row.breakStartDate).toLocaleDateString()}</td><td>{new Date(row.breakEndDate).toLocaleDateString()}</td><td><button className="btn btn-primary" disabled={completeMutation.isPending} onClick={() => completeMutation.mutate(row.id)}>Complete break</button></td></tr>)}{!(active || []).length && <tr><td colSpan={4} style={{ textAlign: 'center', padding: 20 }}>No active service breaks.</td></tr>}</tbody></table></div></div></div>;
};
